-- Minimal Supabase contracts for an isolated PostgreSQL test database.
create role anon nologin;
create role authenticated nologin;
create role supabase_auth_admin nologin;
create schema auth;
create table auth.users (id uuid primary key, email text unique, raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;
grant usage on schema auth to authenticated;
grant execute on function auth.uid() to authenticated;
create table public."Users" (user_id bigint generated by default as identity primary key, username text not null);
-- Simulate an old overly broad policy: the migration must still isolate users.
alter table public."Users" enable row level security;
create policy legacy_read_all on public."Users" for select to authenticated using (true);
grant all on public."Users" to anon, authenticated;
