begin;

-- Retain the numeric profile key used by existing code. Auth has its own UUID.
create table if not exists public."Users" (
  user_id bigint generated by default as identity primary key,
  username text not null
);
alter table public."Users"
  add column auth_user_id uuid unique references auth.users(id) on delete cascade;

-- Existing demo rows remain unlinked. Only authenticated profiles reserve names.
create unique index users_auth_username_unique
  on public."Users" (lower(username)) where auth_user_id is not null;

create function public.create_auth_profile() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  canonical_username text;
begin
  canonical_username := substring(new.email from '^([a-z0-9_]{3,32})@accounts[.]cookmarked[.]edw20009[.]workers[.]dev$');
  if canonical_username is null then
    raise exception 'Invalid Cookmarked account identifier' using errcode = '23514';
  end if;
  -- Derive from the canonical identifier, never from editable user metadata.
  insert into public."Users" (username, auth_user_id) values (canonical_username, new.id);
  return new;
end;
$$;
revoke all on function public.create_auth_profile() from public, anon, authenticated;
create trigger cookmarked_create_auth_profile
  after insert on auth.users for each row execute function public.create_auth_profile();

create function public.keep_auth_identifier() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.email is distinct from old.email then
    raise exception 'Cookmarked account identifiers cannot be changed' using errcode = '23514';
  end if;
  return new;
end;
$$;
revoke all on function public.keep_auth_identifier() from public, anon, authenticated;
create trigger cookmarked_keep_auth_identifier
  before update of email on auth.users for each row execute function public.keep_auth_identifier();

alter table public."Users" enable row level security;
revoke all on public."Users" from public, anon, authenticated;
grant select on public."Users" to authenticated;
create policy users_read_own on public."Users"
  for select to authenticated using ((select auth.uid()) = auth_user_id);
-- Restrictive policies AND with existing permissive policies, preventing leaks.
create policy users_owner_boundary on public."Users" as restrictive
  for all to authenticated
  using ((select auth.uid()) = auth_user_id)
  with check ((select auth.uid()) = auth_user_id);

-- Select this function as the Send Email hook in Supabase Auth settings.
-- Returning success without a delivery operation suppresses authentication mail.
create function public.suppress_auth_email(event jsonb) returns jsonb
language sql as $$ select '{}'::jsonb $$;
revoke all on function public.suppress_auth_email(jsonb) from public, anon, authenticated;
grant usage on schema public to supabase_auth_admin;
grant execute on function public.suppress_auth_email(jsonb) to supabase_auth_admin;

commit;
